export const TODO_DELETE = "TODO_DELETE"
export const TODO_DONE = "TODO_DONE"
export const TODO_ADD = "TODO_ADD"
export const TODO_FILTER = "TODO_FILTER"
export const TODO_SAVE = "TODO_SAVE"
export const TODO_EDIT = "TODO_EDIT"
